CREATE OR REPLACE TABLE TCFG_DIA_UTIL
(
	ID_PK				NUMBER	NOT NULL,
	DT_FERI				DATE				 ,
	DT_PROX_DIA_UTIL	DATE 		 NOT NULL,
	DT_ANTER_DIA    	DATE 		 NOT NULL,
	DS_FERI				VARCHAR(100) 		 ,
	DT_PROCM			DATE		 NOT NULL
);

INSERT INTO TCFG_DIA_UTIL(ID_PK, DT_FERI,DT_PROX_DIA_UTIL,DT_ANTER_DIA,DT_PROCM) VALUES (1, TO_DATE('2018/01/01', 'yyyy/mm/dd'),TO_DATE('2018/01/02', 'yyyy/mm/dd'),TO_DATE('2017/12/29', 'yyyy/mm/dd'),sysdate);