-- MAPPED ENTITY DOESNT NEED THE CREATE TABLE
INSERT INTO T_PERSON(ID,NAME) VALUES (1,'JAMES');


-- NOT MAPPED ENTITY NEEDS THE CREATE TABLE
CREATE OR REPLACE TABLE T_NOT_MAPPED
(
	ID				NUMBER	NOT NULL,
	DT_DAY				DATE				 ,
	DT_NEXT_BUSINESS_DAY	DATE 		 NOT NULL
);

INSERT INTO T_NOT_MAPPED(ID, DT_DAY,DT_NEXT_BUSINESS_DAY) VALUES (1, TO_DATE('2018/01/01', 'yyyy/mm/dd'),TO_DATE('2018/01/02', 'yyyy/mm/dd'));